; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = boards
src_dir = src
; change to T5-ePaper if you have ESP32-WROVER based device (or use 'pio run -e T5-ePaper')
default_envs = T5-ePaper-S3
;default_envs = T5-ePaper

[env]
;lib_extra_dirs = ${PROJECT_DIR}
platform = espressif32@>=6.0.0
framework = arduino
board_build.filesystem = littlefs
;upload_port = /dev/ttyUSB0
upload_speed = 921600
monitor_speed = 115200
build_flags = 
	-DBOARD_HAS_PSRAM
	-DCORE_DEBUG_LEVEL=0

; Do I want this?
monitor_filters = 
	default
	esp32_exception_decoder

	; removed what I don't need
lib_deps = 
	https://github.com/Xinyuan-LilyGO/LilyGo-EPD47.git#esp32s3
;	lewisxhe/SensorLib @ 0.3.1
;	lennarthennigs/Button2 @ 2.3.2
	Wire
;	SPI
    bblanchon/ArduinoJson@^7.4.2

[env:T5-ePaper-S3]
extends = env
board = T5-ePaper-S3
build_flags = ${env.build_flags}
	-DLILYGO_T5_EPD47_S3
	-DARDUINO_USB_CDC_ON_BOOT=1

; older ESP32-WROVER-E device. Note: not all examples fully work.
; https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/issues/177#issuecomment-3747498636
; T5_47_DEV is for my use, not sure why WAKEUP_ANY_LW is for???
; also don't know what the LILYO defines are used for
[env:T5-ePaper]
extends = env
board = T5-ePaper
upload_speed = 460800
build_flags = ${env.build_flags}
	-DLILYGO_T5_EPD47
	-DT5_47_DEV
	-DESP_EXT1_WAKEUP_ANY_LOW=ESP_EXT1_WAKEUP_ALL_LOW
